// <auto-generated />
namespace Moonlit.Mvc.Maintenance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddSystemJob : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSystemJob));
        
        string IMigrationMetadata.Id
        {
            get { return "201508200052571_AddSystemJob"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
