//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://192.168.1.155/services/RemoteSendSMS", ConfigurationName="RemoteSendSMS")]
public interface RemoteSendSMS
{
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://send.axis.webservice.service.mcc.roya.com) of message sendSMSRequest does not match the default value (http://192.168.1.155/services/RemoteSendSMS)
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    sendSMSResponse sendSMS(sendSMSRequest request);
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://send.axis.webservice.service.mcc.roya.com) of message sendSMSRequest1 does not match the default value (http://192.168.1.155/services/RemoteSendSMS)
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    sendSMSResponse1 sendSMS1(sendSMSRequest1 request);
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://send.axis.webservice.service.mcc.roya.com) of message sendSMSRequest2 does not match the default value (http://192.168.1.155/services/RemoteSendSMS)
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    sendSMSResponse2 sendSMS2(sendSMSRequest2 request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="sendSMS", WrapperNamespace="http://send.axis.webservice.service.mcc.roya.com", IsWrapped=true)]
public partial class sendSMSRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string exNumber;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string phone;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string msg;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public int timeFlag;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public long smsTime;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public string msgFlag;
    
    public sendSMSRequest()
    {
    }
    
    public sendSMSRequest(string exNumber, string phone, string msg, int timeFlag, long smsTime, string msgFlag)
    {
        this.exNumber = exNumber;
        this.phone = phone;
        this.msg = msg;
        this.timeFlag = timeFlag;
        this.smsTime = smsTime;
        this.msgFlag = msgFlag;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSResponse", WrapperNamespace="http://192.168.1.155/services/RemoteSendSMS", IsWrapped=true)]
public partial class sendSMSResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int sendSMSReturn;
    
    public sendSMSResponse()
    {
    }
    
    public sendSMSResponse(int sendSMSReturn)
    {
        this.sendSMSReturn = sendSMSReturn;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="sendSMS", WrapperNamespace="http://send.axis.webservice.service.mcc.roya.com", IsWrapped=true)]
public partial class sendSMSRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string exNumber;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string[] phone;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string msg;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public int timeFlag;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public long smsTime;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public string msgFlag;
    
    public sendSMSRequest1()
    {
    }
    
    public sendSMSRequest1(string exNumber, string[] phone, string msg, int timeFlag, long smsTime, string msgFlag)
    {
        this.exNumber = exNumber;
        this.phone = phone;
        this.msg = msg;
        this.timeFlag = timeFlag;
        this.smsTime = smsTime;
        this.msgFlag = msgFlag;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSResponse", WrapperNamespace="http://192.168.1.155/services/RemoteSendSMS", IsWrapped=true)]
public partial class sendSMSResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int sendSMSReturn;
    
    public sendSMSResponse1()
    {
    }
    
    public sendSMSResponse1(int sendSMSReturn)
    {
        this.sendSMSReturn = sendSMSReturn;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="sendSMS", WrapperNamespace="http://send.axis.webservice.service.mcc.roya.com", IsWrapped=true)]
public partial class sendSMSRequest2
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string requestXML;
    
    public sendSMSRequest2()
    {
    }
    
    public sendSMSRequest2(string requestXML)
    {
        this.requestXML = requestXML;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSResponse", WrapperNamespace="http://192.168.1.155/services/RemoteSendSMS", IsWrapped=true)]
public partial class sendSMSResponse2
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string sendSMSReturn;
    
    public sendSMSResponse2()
    {
    }
    
    public sendSMSResponse2(string sendSMSReturn)
    {
        this.sendSMSReturn = sendSMSReturn;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface RemoteSendSMSChannel : RemoteSendSMS, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RemoteSendSMSClient : System.ServiceModel.ClientBase<RemoteSendSMS>, RemoteSendSMS
{
    
    public RemoteSendSMSClient()
    {
    }
    
    public RemoteSendSMSClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RemoteSendSMSClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RemoteSendSMSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RemoteSendSMSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    sendSMSResponse RemoteSendSMS.sendSMS(sendSMSRequest request)
    {
        return base.Channel.sendSMS(request);
    }
    
    public int sendSMS(string exNumber, string phone, string msg, int timeFlag, long smsTime, string msgFlag)
    {
        sendSMSRequest inValue = new sendSMSRequest();
        inValue.exNumber = exNumber;
        inValue.phone = phone;
        inValue.msg = msg;
        inValue.timeFlag = timeFlag;
        inValue.smsTime = smsTime;
        inValue.msgFlag = msgFlag;
        sendSMSResponse retVal = ((RemoteSendSMS)(this)).sendSMS(inValue);
        return retVal.sendSMSReturn;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    sendSMSResponse1 RemoteSendSMS.sendSMS1(sendSMSRequest1 request)
    {
        return base.Channel.sendSMS1(request);
    }
    
    public int sendSMS1(string exNumber, string[] phone, string msg, int timeFlag, long smsTime, string msgFlag)
    {
        sendSMSRequest1 inValue = new sendSMSRequest1();
        inValue.exNumber = exNumber;
        inValue.phone = phone;
        inValue.msg = msg;
        inValue.timeFlag = timeFlag;
        inValue.smsTime = smsTime;
        inValue.msgFlag = msgFlag;
        sendSMSResponse1 retVal = ((RemoteSendSMS)(this)).sendSMS1(inValue);
        return retVal.sendSMSReturn;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    sendSMSResponse2 RemoteSendSMS.sendSMS2(sendSMSRequest2 request)
    {
        return base.Channel.sendSMS2(request);
    }
    
    public string sendSMS2(string requestXML)
    {
        sendSMSRequest2 inValue = new sendSMSRequest2();
        inValue.requestXML = requestXML;
        sendSMSResponse2 retVal = ((RemoteSendSMS)(this)).sendSMS2(inValue);
        return retVal.sendSMSReturn;
    }
}
